/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type AddLiquidityParamsStruct = {
  poolId: BytesLike;
  amount0: BigNumberish;
  amount1: BigNumberish;
  amount0Min: BigNumberish;
  amount1Min: BigNumberish;
  level: BigNumberish;
  source: AddressLike;
  deadline: BigNumberish;
};

export type AddLiquidityParamsStructOutput = [
  poolId: string,
  amount0: bigint,
  amount1: bigint,
  amount0Min: bigint,
  amount1Min: bigint,
  level: bigint,
  source: string,
  deadline: bigint
] & {
  poolId: string;
  amount0: bigint;
  amount1: bigint;
  amount0Min: bigint;
  amount1Min: bigint;
  level: bigint;
  source: string;
  deadline: bigint;
};

export type PoolKeyStruct = {
  currency0: AddressLike;
  currency1: AddressLike;
  fee: BigNumberish;
  tickSpacing: BigNumberish;
  hooks: AddressLike;
};

export type PoolKeyStructOutput = [
  currency0: string,
  currency1: string,
  fee: bigint,
  tickSpacing: bigint,
  hooks: string
] & {
  currency0: string;
  currency1: string;
  fee: bigint;
  tickSpacing: bigint;
  hooks: string;
};

export type PoolStatusStruct = {
  blockTimestampLast: BigNumberish;
  realReserve0: BigNumberish;
  realReserve1: BigNumberish;
  mirrorReserve0: BigNumberish;
  mirrorReserve1: BigNumberish;
  marginFee: BigNumberish;
  lendingRealReserve0: BigNumberish;
  lendingRealReserve1: BigNumberish;
  lendingMirrorReserve0: BigNumberish;
  lendingMirrorReserve1: BigNumberish;
  truncatedReserve0: BigNumberish;
  truncatedReserve1: BigNumberish;
  rate0CumulativeLast: BigNumberish;
  rate1CumulativeLast: BigNumberish;
  key: PoolKeyStruct;
};

export type PoolStatusStructOutput = [
  blockTimestampLast: bigint,
  realReserve0: bigint,
  realReserve1: bigint,
  mirrorReserve0: bigint,
  mirrorReserve1: bigint,
  marginFee: bigint,
  lendingRealReserve0: bigint,
  lendingRealReserve1: bigint,
  lendingMirrorReserve0: bigint,
  lendingMirrorReserve1: bigint,
  truncatedReserve0: bigint,
  truncatedReserve1: bigint,
  rate0CumulativeLast: bigint,
  rate1CumulativeLast: bigint,
  key: PoolKeyStructOutput
] & {
  blockTimestampLast: bigint;
  realReserve0: bigint;
  realReserve1: bigint;
  mirrorReserve0: bigint;
  mirrorReserve1: bigint;
  marginFee: bigint;
  lendingRealReserve0: bigint;
  lendingRealReserve1: bigint;
  lendingMirrorReserve0: bigint;
  lendingMirrorReserve1: bigint;
  truncatedReserve0: bigint;
  truncatedReserve1: bigint;
  rate0CumulativeLast: bigint;
  rate1CumulativeLast: bigint;
  key: PoolKeyStructOutput;
};

export type MarginParamsStruct = {
  poolId: BytesLike;
  marginForOne: boolean;
  leverage: BigNumberish;
  marginAmount: BigNumberish;
  borrowAmount: BigNumberish;
  borrowMaxAmount: BigNumberish;
  recipient: AddressLike;
  deadline: BigNumberish;
};

export type MarginParamsStructOutput = [
  poolId: string,
  marginForOne: boolean,
  leverage: bigint,
  marginAmount: bigint,
  borrowAmount: bigint,
  borrowMaxAmount: bigint,
  recipient: string,
  deadline: bigint
] & {
  poolId: string;
  marginForOne: boolean;
  leverage: bigint;
  marginAmount: bigint;
  borrowAmount: bigint;
  borrowMaxAmount: bigint;
  recipient: string;
  deadline: bigint;
};

export type MarginParamsVoStruct = {
  params: MarginParamsStruct;
  marginTotal: BigNumberish;
  minMarginLevel: BigNumberish;
  marginCurrency: AddressLike;
};

export type MarginParamsVoStructOutput = [
  params: MarginParamsStructOutput,
  marginTotal: bigint,
  minMarginLevel: bigint,
  marginCurrency: string
] & {
  params: MarginParamsStructOutput;
  marginTotal: bigint;
  minMarginLevel: bigint;
  marginCurrency: string;
};

export type ReleaseParamsStruct = {
  poolId: BytesLike;
  marginForOne: boolean;
  payer: AddressLike;
  debtAmount: BigNumberish;
  repayAmount: BigNumberish;
  releaseAmount: BigNumberish;
  rawBorrowAmount: BigNumberish;
  deadline: BigNumberish;
};

export type ReleaseParamsStructOutput = [
  poolId: string,
  marginForOne: boolean,
  payer: string,
  debtAmount: bigint,
  repayAmount: bigint,
  releaseAmount: bigint,
  rawBorrowAmount: bigint,
  deadline: bigint
] & {
  poolId: string;
  marginForOne: boolean;
  payer: string;
  debtAmount: bigint;
  repayAmount: bigint;
  releaseAmount: bigint;
  rawBorrowAmount: bigint;
  deadline: bigint;
};

export type RemoveLiquidityParamsStruct = {
  poolId: BytesLike;
  level: BigNumberish;
  liquidity: BigNumberish;
  amount0Min: BigNumberish;
  amount1Min: BigNumberish;
  deadline: BigNumberish;
};

export type RemoveLiquidityParamsStructOutput = [
  poolId: string,
  level: bigint,
  liquidity: bigint,
  amount0Min: bigint,
  amount1Min: bigint,
  deadline: bigint
] & {
  poolId: string;
  level: bigint;
  liquidity: bigint;
  amount0Min: bigint;
  amount1Min: bigint;
  deadline: bigint;
};

export declare namespace IPoolManager {
  export type SwapParamsStruct = {
    zeroForOne: boolean;
    amountSpecified: BigNumberish;
    sqrtPriceLimitX96: BigNumberish;
  };

  export type SwapParamsStructOutput = [
    zeroForOne: boolean,
    amountSpecified: bigint,
    sqrtPriceLimitX96: bigint
  ] & {
    zeroForOne: boolean;
    amountSpecified: bigint;
    sqrtPriceLimitX96: bigint;
  };
}

export interface PairPoolManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "addPositionManager"
      | "collectProtocolFees"
      | "getAmountIn"
      | "getAmountOut"
      | "getReserves"
      | "getStatus"
      | "handleAddLiquidity"
      | "handleCollectFees"
      | "handleMargin"
      | "handleRelease"
      | "handleRemoveLiquidity"
      | "handleSwapMirror"
      | "hooks"
      | "initialize"
      | "lendingPoolManager"
      | "margin"
      | "marginFees"
      | "marginLiquidity"
      | "mirrorInRealOut"
      | "mirrorTokenManager"
      | "owner"
      | "poolManager"
      | "positionManagers"
      | "release"
      | "removeLiquidity"
      | "removePositionManager"
      | "setBalances"
      | "setHooks"
      | "setStatusManager"
      | "statusManager"
      | "swap"
      | "swapMirror"
      | "transferOwnership"
      | "unlockCallback"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Burn"
      | "Fees"
      | "Initialize"
      | "Mint"
      | "OwnershipTransferred"
      | "Release"
      | "Swap"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [AddLiquidityParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addPositionManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectProtocolFees",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountIn",
    values: [BytesLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [BytesLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleAddLiquidity",
    values: [AddressLike, PoolKeyStruct, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleCollectFees",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleMargin",
    values: [AddressLike, AddressLike, PoolStatusStruct, MarginParamsVoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "handleRelease",
    values: [AddressLike, PoolStatusStruct, ReleaseParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "handleRemoveLiquidity",
    values: [AddressLike, PoolKeyStruct, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleSwapMirror",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hooks", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PoolKeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "lendingPoolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "margin",
    values: [AddressLike, PoolStatusStruct, MarginParamsVoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "marginFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marginLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mirrorInRealOut",
    values: [BytesLike, PoolStatusStruct, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mirrorTokenManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positionManagers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [AddressLike, PoolStatusStruct, ReleaseParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [RemoveLiquidityParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "removePositionManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBalances",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setHooks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStatusManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "statusManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [AddressLike, PoolKeyStruct, IPoolManager.SwapParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapMirror",
    values: [AddressLike, BytesLike, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCallback",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectProtocolFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleCollectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleRemoveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleSwapMirror",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hooks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lendingPoolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "margin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "marginFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marginLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mirrorInRealOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mirrorTokenManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "positionManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setHooks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStatusManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "statusManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapMirror", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCallback",
    data: BytesLike
  ): Result;
}

export namespace BurnEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sender: AddressLike,
    liquidity: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish,
    level: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sender: string,
    liquidity: bigint,
    amount0: bigint,
    amount1: bigint,
    level: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sender: string;
    liquidity: bigint;
    amount0: bigint;
    amount1: bigint;
    level: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesEvent {
  export type InputTuple = [
    poolId: BytesLike,
    currency: AddressLike,
    sender: AddressLike,
    feeType: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    currency: string,
    sender: string,
    feeType: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    poolId: string;
    currency: string;
    sender: string;
    feeType: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializeEvent {
  export type InputTuple = [
    id: BytesLike,
    currency0: AddressLike,
    currency1: AddressLike,
    fee: BigNumberish,
    tickSpacing: BigNumberish,
    hooks: AddressLike
  ];
  export type OutputTuple = [
    id: string,
    currency0: string,
    currency1: string,
    fee: bigint,
    tickSpacing: bigint,
    hooks: string
  ];
  export interface OutputObject {
    id: string;
    currency0: string;
    currency1: string;
    fee: bigint;
    tickSpacing: bigint;
    hooks: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintEvent {
  export type InputTuple = [
    poolId: BytesLike,
    source: AddressLike,
    sender: AddressLike,
    liquidity: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish,
    level: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    source: string,
    sender: string,
    liquidity: bigint,
    amount0: bigint,
    amount1: bigint,
    level: bigint
  ];
  export interface OutputObject {
    poolId: string;
    source: string;
    sender: string;
    liquidity: bigint;
    amount0: bigint;
    amount1: bigint;
    level: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [user: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [user: string, newOwner: string];
  export interface OutputObject {
    user: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseEvent {
  export type InputTuple = [
    poolId: BytesLike,
    borrowCurrency: AddressLike,
    debtAmount: BigNumberish,
    repayAmount: BigNumberish,
    burnAmount: BigNumberish,
    rawBorrowAmount: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    borrowCurrency: string,
    debtAmount: bigint,
    repayAmount: bigint,
    burnAmount: bigint,
    rawBorrowAmount: bigint
  ];
  export interface OutputObject {
    poolId: string;
    borrowCurrency: string;
    debtAmount: bigint;
    repayAmount: bigint;
    burnAmount: bigint;
    rawBorrowAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    poolId: BytesLike,
    sender: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    fee: BigNumberish,
    zeroForOne: boolean,
    feeAmount: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    sender: string,
    amount0: bigint,
    amount1: bigint,
    fee: bigint,
    zeroForOne: boolean,
    feeAmount: bigint
  ];
  export interface OutputObject {
    poolId: string;
    sender: string;
    amount0: bigint;
    amount1: bigint;
    fee: bigint;
    zeroForOne: boolean;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PairPoolManager extends BaseContract {
  connect(runner?: ContractRunner | null): PairPoolManager;
  waitForDeployment(): Promise<this>;

  interface: PairPoolManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [params: AddLiquidityParamsStruct],
    [bigint],
    "payable"
  >;

  addPositionManager: TypedContractMethod<
    [_marginPositionManager: AddressLike],
    [void],
    "nonpayable"
  >;

  collectProtocolFees: TypedContractMethod<
    [recipient: AddressLike, currency: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getAmountIn: TypedContractMethod<
    [poolId: BytesLike, zeroForOne: boolean, amountOut: BigNumberish],
    [bigint],
    "view"
  >;

  getAmountOut: TypedContractMethod<
    [poolId: BytesLike, zeroForOne: boolean, amountIn: BigNumberish],
    [bigint],
    "view"
  >;

  getReserves: TypedContractMethod<
    [poolId: BytesLike],
    [[bigint, bigint] & { _reserve0: bigint; _reserve1: bigint }],
    "view"
  >;

  getStatus: TypedContractMethod<
    [poolId: BytesLike],
    [PoolStatusStructOutput],
    "view"
  >;

  handleAddLiquidity: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  handleCollectFees: TypedContractMethod<
    [recipient: AddressLike, currency: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  handleMargin: TypedContractMethod<
    [
      _positionManager: AddressLike,
      sender: AddressLike,
      status: PoolStatusStruct,
      paramsVo: MarginParamsVoStruct
    ],
    [
      [bigint, bigint, bigint] & {
        marginAmount: bigint;
        marginWithoutFee: bigint;
        borrowAmount: bigint;
      }
    ],
    "nonpayable"
  >;

  handleRelease: TypedContractMethod<
    [
      sender: AddressLike,
      status: PoolStatusStruct,
      params: ReleaseParamsStruct
    ],
    [bigint],
    "nonpayable"
  >;

  handleRemoveLiquidity: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  handleSwapMirror: TypedContractMethod<
    [sender: AddressLike, currency: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  hooks: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<[key: PoolKeyStruct], [void], "nonpayable">;

  lendingPoolManager: TypedContractMethod<[], [string], "view">;

  margin: TypedContractMethod<
    [
      sender: AddressLike,
      status: PoolStatusStruct,
      paramsVo: MarginParamsVoStruct
    ],
    [MarginParamsVoStructOutput],
    "payable"
  >;

  marginFees: TypedContractMethod<[], [string], "view">;

  marginLiquidity: TypedContractMethod<[], [string], "view">;

  mirrorInRealOut: TypedContractMethod<
    [
      poolId: BytesLike,
      status: PoolStatusStruct,
      currency: AddressLike,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  mirrorTokenManager: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolManager: TypedContractMethod<[], [string], "view">;

  positionManagers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  release: TypedContractMethod<
    [
      sender: AddressLike,
      status: PoolStatusStruct,
      params: ReleaseParamsStruct
    ],
    [bigint],
    "payable"
  >;

  removeLiquidity: TypedContractMethod<
    [params: RemoveLiquidityParamsStruct],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;

  removePositionManager: TypedContractMethod<
    [_marginPositionManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setBalances: TypedContractMethod<
    [sender: AddressLike, poolId: BytesLike],
    [PoolStatusStructOutput],
    "nonpayable"
  >;

  setHooks: TypedContractMethod<[_hooks: AddressLike], [void], "nonpayable">;

  setStatusManager: TypedContractMethod<
    [_poolStatusManager: AddressLike],
    [void],
    "nonpayable"
  >;

  statusManager: TypedContractMethod<[], [string], "view">;

  swap: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: IPoolManager.SwapParamsStruct
    ],
    [
      [string, string, bigint, bigint, bigint] & {
        specified: string;
        unspecified: string;
        specifiedAmount: bigint;
        unspecifiedAmount: bigint;
        swapFee: bigint;
      }
    ],
    "nonpayable"
  >;

  swapMirror: TypedContractMethod<
    [
      recipient: AddressLike,
      poolId: BytesLike,
      zeroForOne: boolean,
      amountIn: BigNumberish,
      amountOutMin: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockCallback: TypedContractMethod<
    [data: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [params: AddLiquidityParamsStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "addPositionManager"
  ): TypedContractMethod<
    [_marginPositionManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collectProtocolFees"
  ): TypedContractMethod<
    [recipient: AddressLike, currency: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAmountIn"
  ): TypedContractMethod<
    [poolId: BytesLike, zeroForOne: boolean, amountOut: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [poolId: BytesLike, zeroForOne: boolean, amountIn: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [[bigint, bigint] & { _reserve0: bigint; _reserve1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<[poolId: BytesLike], [PoolStatusStructOutput], "view">;
  getFunction(
    nameOrSignature: "handleAddLiquidity"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleCollectFees"
  ): TypedContractMethod<
    [recipient: AddressLike, currency: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleMargin"
  ): TypedContractMethod<
    [
      _positionManager: AddressLike,
      sender: AddressLike,
      status: PoolStatusStruct,
      paramsVo: MarginParamsVoStruct
    ],
    [
      [bigint, bigint, bigint] & {
        marginAmount: bigint;
        marginWithoutFee: bigint;
        borrowAmount: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleRelease"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      status: PoolStatusStruct,
      params: ReleaseParamsStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleRemoveLiquidity"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleSwapMirror"
  ): TypedContractMethod<
    [sender: AddressLike, currency: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hooks"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[key: PoolKeyStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lendingPoolManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "margin"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      status: PoolStatusStruct,
      paramsVo: MarginParamsVoStruct
    ],
    [MarginParamsVoStructOutput],
    "payable"
  >;
  getFunction(
    nameOrSignature: "marginFees"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "marginLiquidity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mirrorInRealOut"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      status: PoolStatusStruct,
      currency: AddressLike,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mirrorTokenManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positionManagers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      status: PoolStatusStruct,
      params: ReleaseParamsStruct
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [params: RemoveLiquidityParamsStruct],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removePositionManager"
  ): TypedContractMethod<
    [_marginPositionManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBalances"
  ): TypedContractMethod<
    [sender: AddressLike, poolId: BytesLike],
    [PoolStatusStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHooks"
  ): TypedContractMethod<[_hooks: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStatusManager"
  ): TypedContractMethod<
    [_poolStatusManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "statusManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: IPoolManager.SwapParamsStruct
    ],
    [
      [string, string, bigint, bigint, bigint] & {
        specified: string;
        unspecified: string;
        specifiedAmount: bigint;
        unspecifiedAmount: bigint;
        swapFee: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapMirror"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      poolId: BytesLike,
      zeroForOne: boolean,
      amountIn: BigNumberish,
      amountOutMin: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockCallback"
  ): TypedContractMethod<[data: BytesLike], [string], "nonpayable">;

  getEvent(
    key: "Burn"
  ): TypedContractEvent<
    BurnEvent.InputTuple,
    BurnEvent.OutputTuple,
    BurnEvent.OutputObject
  >;
  getEvent(
    key: "Fees"
  ): TypedContractEvent<
    FeesEvent.InputTuple,
    FeesEvent.OutputTuple,
    FeesEvent.OutputObject
  >;
  getEvent(
    key: "Initialize"
  ): TypedContractEvent<
    InitializeEvent.InputTuple,
    InitializeEvent.OutputTuple,
    InitializeEvent.OutputObject
  >;
  getEvent(
    key: "Mint"
  ): TypedContractEvent<
    MintEvent.InputTuple,
    MintEvent.OutputTuple,
    MintEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Release"
  ): TypedContractEvent<
    ReleaseEvent.InputTuple,
    ReleaseEvent.OutputTuple,
    ReleaseEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;

  filters: {
    "Burn(bytes32,address,uint256,uint256,uint256,uint8)": TypedContractEvent<
      BurnEvent.InputTuple,
      BurnEvent.OutputTuple,
      BurnEvent.OutputObject
    >;
    Burn: TypedContractEvent<
      BurnEvent.InputTuple,
      BurnEvent.OutputTuple,
      BurnEvent.OutputObject
    >;

    "Fees(bytes32,address,address,uint8,uint256)": TypedContractEvent<
      FeesEvent.InputTuple,
      FeesEvent.OutputTuple,
      FeesEvent.OutputObject
    >;
    Fees: TypedContractEvent<
      FeesEvent.InputTuple,
      FeesEvent.OutputTuple,
      FeesEvent.OutputObject
    >;

    "Initialize(bytes32,address,address,uint24,int24,address)": TypedContractEvent<
      InitializeEvent.InputTuple,
      InitializeEvent.OutputTuple,
      InitializeEvent.OutputObject
    >;
    Initialize: TypedContractEvent<
      InitializeEvent.InputTuple,
      InitializeEvent.OutputTuple,
      InitializeEvent.OutputObject
    >;

    "Mint(bytes32,address,address,uint256,uint256,uint256,uint8)": TypedContractEvent<
      MintEvent.InputTuple,
      MintEvent.OutputTuple,
      MintEvent.OutputObject
    >;
    Mint: TypedContractEvent<
      MintEvent.InputTuple,
      MintEvent.OutputTuple,
      MintEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Release(bytes32,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ReleaseEvent.InputTuple,
      ReleaseEvent.OutputTuple,
      ReleaseEvent.OutputObject
    >;
    Release: TypedContractEvent<
      ReleaseEvent.InputTuple,
      ReleaseEvent.OutputTuple,
      ReleaseEvent.OutputObject
    >;

    "Swap(bytes32,address,uint256,uint256,uint24,bool,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
  };
}
